language: node_js

sudo: true

node_js:
  - "8.10.0"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run calculate-coverage

after_success:
  - npm run report-coverage


